name: Setup Workspace

on:
  workflow_call:
    outputs:
      cache-hit:
        value: ${{ jobs.setup.outputs.cache-hit }}
        description: Indicates if cache was restored successfully

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.6.3
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'pnpm'

      - name: Cache PNPM Store
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-

      - name: Install Dependencies (cache missing)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        run: pnpm install --frozen-lockfile --prefer-offline --config.ignore-scripts=true
